name = "chat-mastra-works"
main = ".mastra/output/index.mjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat","nodejs_compat_populate_process_env"]

[build]
command = "mastra build"
watch_dir = ".mastra/output"

# 添加 KV 命名空间（如果需要）
# [[kv_namespaces]]
# binding = "MASTRA_KV"
# id = "your-kv-namespace-id"